/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

#include "header.h"

static int r_gerund(struct SN_env * z);
static int r_verb_particles(struct SN_env * z);
static int r_verb_stem(struct SN_env * z);
static int r_verb_tense_mood(struct SN_env * z);
static int r_verb_number_person(struct SN_env * z);
static int r_deverbative(struct SN_env * z);
static int r_noun_plural(struct SN_env * z);
static int r_noun_double_declination(struct SN_env * z);
static int r_noun(struct SN_env * z);
static int r_noun_impersonal_possessive(struct SN_env * z);
static int r_noun_possessive(struct SN_env * z);
#ifdef __cplusplus
extern "C" {
#endif
extern int kalmyk_UTF_8_stem(struct SN_env * z);
#ifdef __cplusplus
}
#endif
#ifdef __cplusplus
extern "C" {
#endif


extern struct SN_env * kalmyk_UTF_8_create_env(void);
extern void kalmyk_UTF_8_close_env(struct SN_env * z);


#ifdef __cplusplus
}
#endif
static const symbol s_0_0[2] = { 0xD1, 0x87 };
static const symbol s_0_1[4] = { 0xD3, 0x99, 0xD1, 0x87 };
static const symbol s_0_2[4] = { 0xD0, 0xB0, 0xD1, 0x87 };

static const struct among a_0[3] =
{
{ 2, s_0_0, -1, 2, 0},
{ 4, s_0_1, 0, 1, 0},
{ 4, s_0_2, 0, 1, 0}
};

static const symbol s_1_0[4] = { 0xD0, 0xBD, 0xD1, 0x80 };
static const symbol s_1_1[2] = { 0xD1, 0x81 };
static const symbol s_1_2[4] = { 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_3[6] = { 0xD1, 0x87, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_4[6] = { 0xD0, 0xB3, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_5[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_6[6] = { 0xD0, 0xB4, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_7[6] = { 0xD0, 0xBA, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_8[6] = { 0xD0, 0xBC, 0xD1, 0x83, 0xD0, 0xB4 };
static const symbol s_1_9[4] = { 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_10[6] = { 0xD1, 0x87, 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_11[6] = { 0xD0, 0xB3, 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_12[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_13[6] = { 0xD0, 0xB4, 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_14[6] = { 0xD0, 0xBA, 0xD2, 0xAF, 0xD0, 0xB4 };
static const symbol s_1_15[6] = { 0xD0, 0xBC, 0xD2, 0xAF, 0xD0, 0xB4 };

static const struct among a_1[16] =
{
{ 4, s_1_0, -1, 6, 0},
{ 2, s_1_1, -1, 1, 0},
{ 4, s_1_2, -1, 5, 0},
{ 6, s_1_3, 2, 5, 0},
{ 6, s_1_4, 2, 3, 0},
{ 8, s_1_5, 4, 2, 0},
{ 6, s_1_6, 2, 5, 0},
{ 6, s_1_7, 2, 4, 0},
{ 6, s_1_8, 2, 5, 0},
{ 4, s_1_9, -1, 5, 0},
{ 6, s_1_10, 9, 5, 0},
{ 6, s_1_11, 9, 3, 0},
{ 8, s_1_12, 11, 2, 0},
{ 6, s_1_13, 9, 5, 0},
{ 6, s_1_14, 9, 4, 0},
{ 6, s_1_15, 9, 5, 0}
};

static const symbol s_2_0[4] = { 0xD1, 0x8B, 0xD0, 0xBD };
static const symbol s_2_1[4] = { 0xD3, 0x99, 0xD0, 0xBD };
static const symbol s_2_2[4] = { 0xD0, 0xB0, 0xD0, 0xBD };
static const symbol s_2_3[4] = { 0xD0, 0xB8, 0xD0, 0xBD };

static const struct among a_2[4] =
{
{ 4, s_2_0, -1, -1, 0},
{ 4, s_2_1, -1, -1, 0},
{ 4, s_2_2, -1, -1, 0},
{ 4, s_2_3, -1, -1, 0}
};

static const symbol s_3_0[4] = { 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_3_1[2] = { 0xD0, 0xBC };
static const symbol s_3_2[4] = { 0xD1, 0x82, 0xD0, 0xBD };
static const symbol s_3_3[4] = { 0xD1, 0x87, 0xD0, 0xBD };
static const symbol s_3_4[6] = { 0xD0, 0xBC, 0xD0, 0xB4, 0xD0, 0xBD };

static const struct among a_3[5] =
{
{ 4, s_3_0, -1, 1, 0},
{ 2, s_3_1, -1, 2, 0},
{ 4, s_3_2, -1, 2, 0},
{ 4, s_3_3, -1, 2, 0},
{ 6, s_3_4, -1, 2, 0}
};

static const symbol s_4_0[2] = { 0xD1, 0x8B };
static const symbol s_4_1[2] = { 0xD3, 0x99 };
static const symbol s_4_2[2] = { 0xD0, 0xB0 };
static const symbol s_4_3[2] = { 0xD0, 0xB8 };

static const struct among a_4[4] =
{
{ 2, s_4_0, -1, 2, 0},
{ 2, s_4_1, -1, 1, 0},
{ 2, s_4_2, -1, 1, 0},
{ 2, s_4_3, -1, 2, 0}
};

static const symbol s_5_0[2] = { 0xD1, 0x83 };
static const symbol s_5_1[2] = { 0xD3, 0x99 };
static const symbol s_5_2[4] = { 0xD0, 0xBB, 0xD3, 0x99 };
static const symbol s_5_3[2] = { 0xD2, 0xAF };
static const symbol s_5_4[2] = { 0xD0, 0xB0 };
static const symbol s_5_5[4] = { 0xD0, 0xBB, 0xD0, 0xB0 };

static const struct among a_5[6] =
{
{ 2, s_5_0, -1, 2, 0},
{ 2, s_5_1, -1, 2, 0},
{ 4, s_5_2, 1, 1, 0},
{ 2, s_5_3, -1, 2, 0},
{ 2, s_5_4, -1, 2, 0},
{ 4, s_5_5, 4, 1, 0}
};

static const symbol s_6_0[6] = { 0xD0, 0xBD, 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_6_1[4] = { 0xD1, 0x80, 0xD0, 0xBD };
static const symbol s_6_2[6] = { 0xD3, 0x99, 0xD1, 0x81, 0xD0, 0xBD };
static const symbol s_6_3[6] = { 0xD0, 0xB0, 0xD1, 0x81, 0xD0, 0xBD };
static const symbol s_6_4[4] = { 0xD3, 0x99, 0xD0, 0xBD };
static const symbol s_6_5[4] = { 0xD0, 0xB0, 0xD0, 0xBD };

static const struct among a_6[6] =
{
{ 6, s_6_0, -1, 1, 0},
{ 4, s_6_1, -1, 3, 0},
{ 6, s_6_2, -1, 5, 0},
{ 6, s_6_3, -1, 4, 0},
{ 4, s_6_4, -1, 2, 0},
{ 4, s_6_5, -1, 2, 0}
};

static const symbol s_7_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_7_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_7_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_7_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_7_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_7_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_7_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_7_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_7_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_7_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_7_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_7_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_7[12] =
{
{ 4, s_7_0, -1, 1, 0},
{ 4, s_7_1, -1, 1, 0},
{ 4, s_7_2, -1, 1, 0},
{ 4, s_7_3, -1, 1, 0},
{ 4, s_7_4, -1, 1, 0},
{ 4, s_7_5, -1, 1, 0},
{ 4, s_7_6, -1, 1, 0},
{ 4, s_7_7, -1, 1, 0},
{ 4, s_7_8, -1, 1, 0},
{ 4, s_7_9, -1, 1, 0},
{ 4, s_7_10, -1, 1, 0},
{ 4, s_7_11, -1, 1, 0}
};

static const symbol s_8_0[4] = { 0xD1, 0x82, 0xD3, 0x99 };
static const symbol s_8_1[4] = { 0xD0, 0xBD, 0xD3, 0x99 };
static const symbol s_8_2[4] = { 0xD1, 0x82, 0xD0, 0xB0 };
static const symbol s_8_3[4] = { 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_8_4[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD0, 0xB8, 0xD0, 0xBD };
static const symbol s_8_5[6] = { 0xD2, 0xBB, 0xD0, 0xB8, 0xD0, 0xBD };

static const struct among a_8[6] =
{
{ 4, s_8_0, -1, 4, 0},
{ 4, s_8_1, -1, 1, 0},
{ 4, s_8_2, -1, 4, 0},
{ 4, s_8_3, -1, 1, 0},
{ 8, s_8_4, -1, 2, 0},
{ 6, s_8_5, -1, 3, 0}
};

static const symbol s_9_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_9_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_9_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_9_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_9_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_9_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_9_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_9_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_9_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_9_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_9_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_9_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_9[12] =
{
{ 4, s_9_0, -1, 1, 0},
{ 4, s_9_1, -1, 1, 0},
{ 4, s_9_2, -1, 1, 0},
{ 4, s_9_3, -1, 1, 0},
{ 4, s_9_4, -1, 1, 0},
{ 4, s_9_5, -1, 1, 0},
{ 4, s_9_6, -1, 1, 0},
{ 4, s_9_7, -1, 1, 0},
{ 4, s_9_8, -1, 1, 0},
{ 4, s_9_9, -1, 1, 0},
{ 4, s_9_10, -1, 1, 0},
{ 4, s_9_11, -1, 1, 0}
};

static const symbol s_10_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_10_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_10_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_10_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_10_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_10_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_10_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_10_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_10_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_10_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_10_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_10_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_10[12] =
{
{ 4, s_10_0, -1, 1, 0},
{ 4, s_10_1, -1, 1, 0},
{ 4, s_10_2, -1, 1, 0},
{ 4, s_10_3, -1, 1, 0},
{ 4, s_10_4, -1, 1, 0},
{ 4, s_10_5, -1, 1, 0},
{ 4, s_10_6, -1, 1, 0},
{ 4, s_10_7, -1, 1, 0},
{ 4, s_10_8, -1, 1, 0},
{ 4, s_10_9, -1, 1, 0},
{ 4, s_10_10, -1, 1, 0},
{ 4, s_10_11, -1, 1, 0}
};

static const symbol s_11_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_11_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_11_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_11_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_11_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_11_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_11_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_11_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_11_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_11_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_11_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_11_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_11[12] =
{
{ 4, s_11_0, -1, 1, 0},
{ 4, s_11_1, -1, 1, 0},
{ 4, s_11_2, -1, 1, 0},
{ 4, s_11_3, -1, 1, 0},
{ 4, s_11_4, -1, 1, 0},
{ 4, s_11_5, -1, 1, 0},
{ 4, s_11_6, -1, 1, 0},
{ 4, s_11_7, -1, 1, 0},
{ 4, s_11_8, -1, 1, 0},
{ 4, s_11_9, -1, 1, 0},
{ 4, s_11_10, -1, 1, 0},
{ 4, s_11_11, -1, 1, 0}
};

static const symbol s_12_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_12_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_12_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_12_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_12_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_12_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_12_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_12_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_12_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_12_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_12_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_12_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_12[12] =
{
{ 4, s_12_0, -1, 1, 0},
{ 4, s_12_1, -1, 1, 0},
{ 4, s_12_2, -1, 1, 0},
{ 4, s_12_3, -1, 1, 0},
{ 4, s_12_4, -1, 1, 0},
{ 4, s_12_5, -1, 1, 0},
{ 4, s_12_6, -1, 1, 0},
{ 4, s_12_7, -1, 1, 0},
{ 4, s_12_8, -1, 1, 0},
{ 4, s_12_9, -1, 1, 0},
{ 4, s_12_10, -1, 1, 0},
{ 4, s_12_11, -1, 1, 0}
};

static const symbol s_13_0[2] = { 0xD1, 0x85 };

static const struct among a_13[1] =
{
{ 2, s_13_0, -1, -1, 0}
};

static const symbol s_14_0[4] = { 0xD1, 0x87, 0xD1, 0x83 };
static const symbol s_14_1[4] = { 0xD0, 0xB3, 0xD1, 0x83 };
static const symbol s_14_2[6] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD1, 0x83 };
static const symbol s_14_3[4] = { 0xD0, 0xB4, 0xD1, 0x83 };
static const symbol s_14_4[4] = { 0xD0, 0xBA, 0xD1, 0x83 };
static const symbol s_14_5[4] = { 0xD0, 0xBC, 0xD1, 0x83 };
static const symbol s_14_6[4] = { 0xD1, 0x87, 0xD2, 0xAF };
static const symbol s_14_7[4] = { 0xD0, 0xB3, 0xD2, 0xAF };
static const symbol s_14_8[6] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD2, 0xAF };
static const symbol s_14_9[4] = { 0xD0, 0xB4, 0xD2, 0xAF };
static const symbol s_14_10[4] = { 0xD0, 0xBA, 0xD2, 0xAF };
static const symbol s_14_11[4] = { 0xD0, 0xBC, 0xD2, 0xAF };

static const struct among a_14[12] =
{
{ 4, s_14_0, -1, -1, 0},
{ 4, s_14_1, -1, -1, 0},
{ 6, s_14_2, 1, -1, 0},
{ 4, s_14_3, -1, -1, 0},
{ 4, s_14_4, -1, -1, 0},
{ 4, s_14_5, -1, -1, 0},
{ 4, s_14_6, -1, -1, 0},
{ 4, s_14_7, -1, -1, 0},
{ 6, s_14_8, 7, -1, 0},
{ 4, s_14_9, -1, -1, 0},
{ 4, s_14_10, -1, -1, 0},
{ 4, s_14_11, -1, -1, 0}
};

static const symbol s_15_0[4] = { 0xD1, 0x83, 0xD1, 0x83 };
static const symbol s_15_1[4] = { 0xD1, 0x8B, 0xD1, 0x8B };
static const symbol s_15_2[4] = { 0xD1, 0x8D, 0xD1, 0x8D };
static const symbol s_15_3[4] = { 0xD1, 0x8E, 0xD1, 0x8E };
static const symbol s_15_4[4] = { 0xD1, 0x8F, 0xD1, 0x8F };
static const symbol s_15_5[4] = { 0xD3, 0x99, 0xD3, 0x99 };
static const symbol s_15_6[4] = { 0xD3, 0xA9, 0xD3, 0xA9 };
static const symbol s_15_7[4] = { 0xD2, 0xAF, 0xD2, 0xAF };
static const symbol s_15_8[4] = { 0xD0, 0xB0, 0xD0, 0xB0 };
static const symbol s_15_9[4] = { 0xD0, 0xB5, 0xD0, 0xB5 };
static const symbol s_15_10[4] = { 0xD0, 0xB8, 0xD0, 0xB8 };
static const symbol s_15_11[4] = { 0xD0, 0xBE, 0xD0, 0xBE };

static const struct among a_15[12] =
{
{ 4, s_15_0, -1, 1, 0},
{ 4, s_15_1, -1, 1, 0},
{ 4, s_15_2, -1, 1, 0},
{ 4, s_15_3, -1, 1, 0},
{ 4, s_15_4, -1, 1, 0},
{ 4, s_15_5, -1, 1, 0},
{ 4, s_15_6, -1, 1, 0},
{ 4, s_15_7, -1, 1, 0},
{ 4, s_15_8, -1, 1, 0},
{ 4, s_15_9, -1, 1, 0},
{ 4, s_15_10, -1, 1, 0},
{ 4, s_15_11, -1, 1, 0}
};

static const symbol s_16_0[4] = { 0xD1, 0x83, 0xD1, 0x80 };
static const symbol s_16_1[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD1, 0x83, 0xD1, 0x80 };
static const symbol s_16_2[6] = { 0xD2, 0xBB, 0xD1, 0x83, 0xD1, 0x80 };
static const symbol s_16_3[4] = { 0xD3, 0x99, 0xD1, 0x80 };
static const symbol s_16_4[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD3, 0x99, 0xD1, 0x80 };
static const symbol s_16_5[6] = { 0xD2, 0xBB, 0xD3, 0x99, 0xD1, 0x80 };
static const symbol s_16_6[4] = { 0xD2, 0xAF, 0xD1, 0x80 };
static const symbol s_16_7[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD2, 0xAF, 0xD1, 0x80 };
static const symbol s_16_8[6] = { 0xD2, 0xBB, 0xD2, 0xAF, 0xD1, 0x80 };
static const symbol s_16_9[4] = { 0xD0, 0xB0, 0xD1, 0x80 };
static const symbol s_16_10[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD0, 0xB0, 0xD1, 0x80 };
static const symbol s_16_11[6] = { 0xD2, 0xBB, 0xD0, 0xB0, 0xD1, 0x80 };
static const symbol s_16_12[4] = { 0xD3, 0x99, 0xD1, 0x81 };
static const symbol s_16_13[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD3, 0x99, 0xD1, 0x81 };
static const symbol s_16_14[6] = { 0xD2, 0xBB, 0xD3, 0x99, 0xD1, 0x81 };
static const symbol s_16_15[4] = { 0xD0, 0xB0, 0xD1, 0x81 };
static const symbol s_16_16[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD0, 0xB0, 0xD1, 0x81 };
static const symbol s_16_17[6] = { 0xD2, 0xBB, 0xD0, 0xB0, 0xD1, 0x81 };
static const symbol s_16_18[2] = { 0xD1, 0x82 };
static const symbol s_16_19[4] = { 0xD1, 0x82, 0xD3, 0x99 };
static const symbol s_16_20[4] = { 0xD0, 0xBB, 0xD3, 0x99 };
static const symbol s_16_21[4] = { 0xD0, 0xBD, 0xD3, 0x99 };
static const symbol s_16_22[4] = { 0xD1, 0x82, 0xD0, 0xB0 };
static const symbol s_16_23[4] = { 0xD0, 0xBB, 0xD0, 0xB0 };
static const symbol s_16_24[4] = { 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_16_25[2] = { 0xD0, 0xB3 };
static const symbol s_16_26[4] = { 0xD1, 0x8B, 0xD0, 0xB3 };
static const symbol s_16_27[4] = { 0xD0, 0xB8, 0xD0, 0xB3 };
static const symbol s_16_28[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD0, 0xB8, 0xD0, 0xB3 };
static const symbol s_16_29[2] = { 0xD0, 0xB4 };
static const symbol s_16_30[2] = { 0xD0, 0xBD };
static const symbol s_16_31[4] = { 0xD1, 0x8B, 0xD0, 0xBD };
static const symbol s_16_32[4] = { 0xD0, 0xB8, 0xD0, 0xBD };
static const symbol s_16_33[8] = { 0xD2, 0xA3, 0xD0, 0xB3, 0xD0, 0xB8, 0xD0, 0xBD };
static const symbol s_16_34[6] = { 0xD2, 0xBB, 0xD0, 0xB8, 0xD0, 0xBD };

static const struct among a_16[35] =
{
{ 4, s_16_0, -1, 6, 0},
{ 8, s_16_1, 0, 2, 0},
{ 6, s_16_2, 0, 4, 0},
{ 4, s_16_3, -1, 5, 0},
{ 8, s_16_4, 3, 2, 0},
{ 6, s_16_5, 3, 3, 0},
{ 4, s_16_6, -1, 6, 0},
{ 8, s_16_7, 6, 2, 0},
{ 6, s_16_8, 6, 4, 0},
{ 4, s_16_9, -1, 5, 0},
{ 8, s_16_10, 9, 2, 0},
{ 6, s_16_11, 9, 3, 0},
{ 4, s_16_12, -1, 6, 0},
{ 8, s_16_13, 12, 2, 0},
{ 6, s_16_14, 12, 4, 0},
{ 4, s_16_15, -1, 6, 0},
{ 8, s_16_16, 15, 2, 0},
{ 6, s_16_17, 15, 4, 0},
{ 2, s_16_18, -1, 6, 0},
{ 4, s_16_19, -1, 6, 0},
{ 4, s_16_20, -1, 5, 0},
{ 4, s_16_21, -1, 1, 0},
{ 4, s_16_22, -1, 6, 0},
{ 4, s_16_23, -1, 5, 0},
{ 4, s_16_24, -1, 1, 0},
{ 2, s_16_25, -1, 9, 0},
{ 4, s_16_26, 25, 6, 0},
{ 4, s_16_27, 25, 6, 0},
{ 8, s_16_28, 27, 2, 0},
{ 2, s_16_29, -1, 7, 0},
{ 2, s_16_30, -1, 8, 0},
{ 4, s_16_31, 30, 6, 0},
{ 4, s_16_32, 30, 6, 0},
{ 8, s_16_33, 32, 2, 0},
{ 6, s_16_34, 32, 3, 0}
};

static const symbol s_17_0[4] = { 0xD0, 0xBB, 0xD2, 0xBB };

static const struct among a_17[1] =
{
{ 4, s_17_0, -1, 1, 0}
};

static const symbol s_18_0[4] = { 0xD0, 0xB2, 0xD1, 0x80 };
static const symbol s_18_1[4] = { 0xD0, 0xBB, 0xD1, 0x82 };
static const symbol s_18_2[4] = { 0xD0, 0xB4, 0xD0, 0xB3 };
static const symbol s_18_3[4] = { 0xD0, 0xB4, 0xD0, 0xBB };
static const symbol s_18_4[4] = { 0xD1, 0x81, 0xD0, 0xBD };
static const symbol s_18_5[6] = { 0xD0, 0xBB, 0xD2, 0xBB, 0xD0, 0xBD };

static const struct among a_18[6] =
{
{ 4, s_18_0, -1, 2, 0},
{ 4, s_18_1, -1, 1, 0},
{ 4, s_18_2, -1, 1, 0},
{ 4, s_18_3, -1, 1, 0},
{ 4, s_18_4, -1, 1, 0},
{ 6, s_18_5, -1, 1, 0}
};

static const symbol s_19_0[2] = { 0xD1, 0x81 };
static const symbol s_19_1[2] = { 0xD1, 0x85 };
static const symbol s_19_2[2] = { 0xD0, 0xB4 };

static const struct among a_19[3] =
{
{ 2, s_19_0, -1, 1, 0},
{ 2, s_19_1, -1, 1, 0},
{ 2, s_19_2, -1, 1, 0}
};

static const symbol s_20_0[2] = { 0xD1, 0x81 };
static const symbol s_20_1[2] = { 0xD1, 0x85 };
static const symbol s_20_2[2] = { 0xD0, 0xB4 };

static const struct among a_20[3] =
{
{ 2, s_20_0, -1, 1, 0},
{ 2, s_20_1, -1, 1, 0},
{ 2, s_20_2, -1, 1, 0}
};

static const symbol s_21_0[2] = { 0xD1, 0x88 };
static const symbol s_21_1[2] = { 0xD0, 0xB4 };
static const symbol s_21_2[2] = { 0xD0, 0xBB };

static const struct among a_21[3] =
{
{ 2, s_21_0, -1, 1, 0},
{ 2, s_21_1, -1, 1, 0},
{ 2, s_21_2, -1, 1, 0}
};

static const symbol s_22_0[4] = { 0xD1, 0x85, 0xD1, 0x88 };
static const symbol s_22_1[6] = { 0xD1, 0x85, 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_22_2[8] = { 0xD1, 0x85, 0xD0, 0xB8, 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_22_3[4] = { 0xD0, 0xBC, 0xD0, 0xB1 };
static const symbol s_22_4[4] = { 0xD0, 0xBC, 0xD0, 0xBD };
static const symbol s_22_5[4] = { 0xD0, 0xB3, 0xD0, 0xBE };

static const struct among a_22[6] =
{
{ 4, s_22_0, -1, 3, 0},
{ 6, s_22_1, -1, 4, 0},
{ 8, s_22_2, -1, 4, 0},
{ 4, s_22_3, -1, 1, 0},
{ 4, s_22_4, -1, 1, 0},
{ 4, s_22_5, -1, 2, 0}
};

static const symbol s_23_0[2] = { 0xD1, 0x83 };
static const symbol s_23_1[2] = { 0xD2, 0xAF };

static const struct among a_23[2] =
{
{ 2, s_23_0, -1, 1, 0},
{ 2, s_23_1, -1, 1, 0}
};

static const symbol s_24_0[2] = { 0xD1, 0x82 };
static const symbol s_24_1[2] = { 0xD1, 0x87 };
static const symbol s_24_2[2] = { 0xD0, 0xB2 };
static const symbol s_24_3[8] = { 0xD0, 0xB2, 0xD0, 0xB8, 0xD0, 0xB4, 0xD0, 0xBD };

static const struct among a_24[4] =
{
{ 2, s_24_0, -1, 2, 0},
{ 2, s_24_1, -1, 2, 0},
{ 2, s_24_2, -1, 1, 0},
{ 8, s_24_3, -1, 1, 0}
};

static const symbol s_25_0[2] = { 0xD1, 0x85 };

static const struct among a_25[1] =
{
{ 2, s_25_0, -1, -1, 0}
};

static const symbol s_26_0[4] = { 0xD1, 0x81, 0xD1, 0x83 };
static const symbol s_26_1[2] = { 0xD1, 0x85 };
static const symbol s_26_2[2] = { 0xD1, 0x87 };
static const symbol s_26_3[4] = { 0xD0, 0xB8, 0xD1, 0x8F };
static const symbol s_26_4[2] = { 0xD2, 0x97 };
static const symbol s_26_5[4] = { 0xD1, 0x81, 0xD3, 0x99 };
static const symbol s_26_6[6] = { 0xD1, 0x82, 0xD1, 0x85, 0xD3, 0x99 };
static const symbol s_26_7[6] = { 0xD0, 0xB2, 0xD0, 0xB7, 0xD3, 0x99 };
static const symbol s_26_8[4] = { 0xD0, 0xBB, 0xD3, 0x99 };
static const symbol s_26_9[4] = { 0xD0, 0xBD, 0xD3, 0x99 };
static const symbol s_26_10[8] = { 0xD2, 0x97, 0xD3, 0x99, 0xD0, 0xBD, 0xD3, 0x99 };
static const symbol s_26_11[4] = { 0xD1, 0x81, 0xD2, 0xAF };
static const symbol s_26_12[4] = { 0xD1, 0x81, 0xD0, 0xB0 };
static const symbol s_26_13[6] = { 0xD1, 0x82, 0xD1, 0x85, 0xD0, 0xB0 };
static const symbol s_26_14[6] = { 0xD0, 0xB2, 0xD0, 0xB7, 0xD0, 0xB0 };
static const symbol s_26_15[4] = { 0xD0, 0xBB, 0xD0, 0xB0 };
static const symbol s_26_16[4] = { 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_26_17[8] = { 0xD1, 0x87, 0xD0, 0xB0, 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_26_18[8] = { 0xD2, 0x97, 0xD0, 0xB0, 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_26_19[2] = { 0xD0, 0xB9 };
static const symbol s_26_20[4] = { 0xD0, 0xB8, 0xD0, 0xB9 };
static const symbol s_26_21[4] = { 0xD1, 0x81, 0xD0, 0xBD };
static const symbol s_26_22[4] = { 0xD1, 0x82, 0xD0, 0xBD };
static const symbol s_26_23[6] = { 0xD1, 0x81, 0xD0, 0xBC, 0xD0, 0xBD };

static const struct among a_26[24] =
{
{ 4, s_26_0, -1, 1, 0},
{ 2, s_26_1, -1, 1, 0},
{ 2, s_26_2, -1, 1, 0},
{ 4, s_26_3, -1, 1, 0},
{ 2, s_26_4, -1, 1, 0},
{ 4, s_26_5, -1, 1, 0},
{ 6, s_26_6, -1, 1, 0},
{ 6, s_26_7, -1, 1, 0},
{ 4, s_26_8, -1, 2, 0},
{ 4, s_26_9, -1, 1, 0},
{ 8, s_26_10, 9, 1, 0},
{ 4, s_26_11, -1, 1, 0},
{ 4, s_26_12, -1, 1, 0},
{ 6, s_26_13, -1, 1, 0},
{ 6, s_26_14, -1, 1, 0},
{ 4, s_26_15, -1, 2, 0},
{ 4, s_26_16, -1, 1, 0},
{ 8, s_26_17, 16, 1, 0},
{ 8, s_26_18, 16, 1, 0},
{ 2, s_26_19, -1, 1, 0},
{ 4, s_26_20, 19, 1, 0},
{ 4, s_26_21, -1, 1, 0},
{ 4, s_26_22, -1, 1, 0},
{ 6, s_26_23, -1, 1, 0}
};

static const symbol s_27_0[4] = { 0xD0, 0xB4, 0xD1, 0x85 };
static const symbol s_27_1[4] = { 0xD0, 0xBB, 0xD1, 0x86 };
static const symbol s_27_2[6] = { 0xD1, 0x86, 0xD1, 0x85, 0xD3, 0x99 };
static const symbol s_27_3[4] = { 0xD2, 0x97, 0xD3, 0x99 };
static const symbol s_27_4[6] = { 0xD1, 0x86, 0xD1, 0x85, 0xD0, 0xB0 };
static const symbol s_27_5[4] = { 0xD2, 0x97, 0xD0, 0xB0 };
static const symbol s_27_6[4] = { 0xD1, 0x80, 0xD0, 0xB3 };
static const symbol s_27_7[4] = { 0xD0, 0xB3, 0xD0, 0xB4 };
static const symbol s_27_8[4] = { 0xD0, 0xBB, 0xD0, 0xB4 };
static const symbol s_27_9[4] = { 0xD0, 0xBB, 0xD0, 0xB7 };
static const symbol s_27_10[4] = { 0xD1, 0x81, 0xD0, 0xBA };
static const symbol s_27_11[4] = { 0xD1, 0x87, 0xD0, 0xBA };
static const symbol s_27_12[4] = { 0xD1, 0x83, 0xD0, 0xBB };
static const symbol s_27_13[4] = { 0xD2, 0xAF, 0xD0, 0xBB };
static const symbol s_27_14[4] = { 0xD0, 0xBB, 0xD2, 0xBB };

static const struct among a_27[15] =
{
{ 4, s_27_0, -1, 3, 0},
{ 4, s_27_1, -1, 1, 0},
{ 6, s_27_2, -1, 1, 0},
{ 4, s_27_3, -1, 1, 0},
{ 6, s_27_4, -1, 1, 0},
{ 4, s_27_5, -1, 1, 0},
{ 4, s_27_6, -1, 2, 0},
{ 4, s_27_7, -1, 1, 0},
{ 4, s_27_8, -1, 1, 0},
{ 4, s_27_9, -1, 1, 0},
{ 4, s_27_10, -1, 4, 0},
{ 4, s_27_11, -1, 1, 0},
{ 4, s_27_12, -1, 1, 0},
{ 4, s_27_13, -1, 1, 0},
{ 4, s_27_14, -1, 1, 0}
};

static const symbol s_28_0[6] = { 0xD1, 0x85, 0xD3, 0x99, 0xD1, 0x80 };
static const symbol s_28_1[6] = { 0xD1, 0x85, 0xD0, 0xB0, 0xD1, 0x80 };
static const symbol s_28_2[4] = { 0xD0, 0xB3, 0xD1, 0x87 };
static const symbol s_28_3[10] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD3, 0x99, 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_28_4[10] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD0, 0xB0, 0xD0, 0xBD, 0xD1, 0x8C };
static const symbol s_28_5[8] = { 0xD1, 0x81, 0xD3, 0x99, 0xD1, 0x80, 0xD3, 0x99 };
static const symbol s_28_6[6] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD3, 0x99 };
static const symbol s_28_7[8] = { 0xD1, 0x81, 0xD0, 0xB0, 0xD1, 0x80, 0xD0, 0xB0 };
static const symbol s_28_8[6] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD0, 0xB0 };
static const symbol s_28_9[6] = { 0xD1, 0x81, 0xD0, 0xBD, 0xD0, 0xB0 };
static const symbol s_28_10[4] = { 0xD0, 0xB4, 0xD0, 0xB3 };
static const symbol s_28_11[4] = { 0xD3, 0x99, 0xD0, 0xB4 };
static const symbol s_28_12[6] = { 0xD2, 0xBB, 0xD3, 0x99, 0xD0, 0xB4 };
static const symbol s_28_13[4] = { 0xD0, 0xB0, 0xD0, 0xB4 };
static const symbol s_28_14[6] = { 0xD2, 0xBB, 0xD0, 0xB0, 0xD0, 0xB4 };
static const symbol s_28_15[4] = { 0xD1, 0x82, 0xD0, 0xBB };
static const symbol s_28_16[10] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD3, 0x99, 0xD1, 0x80, 0xD0, 0xBD };
static const symbol s_28_17[10] = { 0xD1, 0x85, 0xD0, 0xBB, 0xD0, 0xB0, 0xD1, 0x80, 0xD0, 0xBD };
static const symbol s_28_18[4] = { 0xD1, 0x81, 0xD0, 0xBD };
static const symbol s_28_19[6] = { 0xD0, 0xB2, 0xD1, 0x87, 0xD0, 0xBD };

static const struct among a_28[20] =
{
{ 6, s_28_0, -1, 2, 0},
{ 6, s_28_1, -1, 2, 0},
{ 4, s_28_2, -1, 2, 0},
{ 10, s_28_3, -1, 2, 0},
{ 10, s_28_4, -1, 2, 0},
{ 8, s_28_5, -1, 2, 0},
{ 6, s_28_6, -1, 2, 0},
{ 8, s_28_7, -1, 2, 0},
{ 6, s_28_8, -1, 2, 0},
{ 6, s_28_9, -1, 3, 0},
{ 4, s_28_10, -1, 2, 0},
{ 4, s_28_11, -1, 2, 0},
{ 6, s_28_12, 11, 1, 0},
{ 4, s_28_13, -1, 2, 0},
{ 6, s_28_14, 13, 1, 0},
{ 4, s_28_15, -1, 2, 0},
{ 10, s_28_16, -1, 2, 0},
{ 10, s_28_17, -1, 2, 0},
{ 4, s_28_18, -1, 3, 0},
{ 6, s_28_19, -1, 3, 0}
};

static const unsigned char g_vowel[] = { 33, 65, 8, 232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 2, 0, 2 };

static const symbol s_0[] = { 0xD2, 0xA3 };
static const symbol s_1[] = { 0xD0, 0xB3 };
static const symbol s_2[] = { 0xD0, 0xBA };
static const symbol s_3[] = { 0xD0, 0xB8 };
static const symbol s_4[] = { 0xD0, 0xBD };
static const symbol s_5[] = { 0xD2, 0xBB };
static const symbol s_6[] = { 0xD1, 0x80 };
static const symbol s_7[] = { 0xD0, 0xB0, 0xD1, 0x81 };
static const symbol s_8[] = { 0xD3, 0x99, 0xD1, 0x81 };
static const symbol s_9[] = { 0xD0, 0xBD };
static const symbol s_10[] = { 0xD2, 0xA3 };
static const symbol s_11[] = { 0xD0, 0xBD };
static const symbol s_12[] = { 0xD2, 0xA3 };
static const symbol s_13[] = { 0xD1, 0x80 };
static const symbol s_14[] = { 0xD0, 0xB4 };
static const symbol s_15[] = { 0xD1, 0x81 };

static int r_noun_plural(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_1, 16);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 2, s_0);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 2, s_1);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 2, s_2);
                if (ret < 0) return ret;
            }
            break;
        case 5:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 6:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test1 = z->l - z->c;
                if (z->c - 1 <= z->lb || z->p[z->c - 1] != 135) return 0;
                among_var = find_among_b(z, a_0, 3);
                if (!(among_var)) return 0;
                z->c = z->l - m_test1;
            }
            switch (among_var) {
                case 1:
                    z->ket = z->c;
                    {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                        if (ret < 0) return 0;
                        z->c = ret;
                    }
                    z->bra = z->c;
                    {   int ret = slice_del(z);
                        if (ret < 0) return ret;
                    }
                    break;
                case 2:
                    z->ket = z->c;
                    {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                        if (ret < 0) return 0;
                        z->c = ret;
                    }
                    z->bra = z->c;
                    {   int ret = slice_del(z);
                        if (ret < 0) return ret;
                    }
                    break;
            }
            break;
    }
    return 1;
}

static int r_noun_possessive(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_3, 5);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int m_test1 = z->l - z->c;
                {   int m2 = z->l - z->c; (void)m2;
                    if (z->c - 3 <= z->lb || z->p[z->c - 1] != 189) goto lab0;
                    if (!(find_among_b(z, a_2, 4))) goto lab0;
                    return 0;
                lab0:
                    z->c = z->l - m2;
                }
                z->c = z->l - m_test1;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test3 = z->l - z->c;
                if (!(eq_s_b(z, 2, s_3))) return 0;
                z->c = z->l - m_test3;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_noun_impersonal_possessive(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    if (z->c - 3 <= z->lb || (z->p[z->c - 1] != 140 && z->p[z->c - 1] != 189)) return 0;
    among_var = find_among_b(z, a_6, 6);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int m_test1 = z->l - z->c;
                among_var = find_among_b(z, a_4, 4);
                if (!(among_var)) return 0;
                z->c = z->l - m_test1;
            }
            switch (among_var) {
                case 1:
                    {   int ret = slice_del(z);
                        if (ret < 0) return ret;
                    }
                    break;
                case 2:
                    {   int ret = slice_from_s(z, 2, s_4);
                        if (ret < 0) return ret;
                    }
                    break;
            }
            break;
        case 2:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test2 = z->l - z->c;
                if (!(eq_s_b(z, 2, s_5))) return 0;
                z->c = z->l - m_test2;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int m_test3 = z->l - z->c;
                among_var = find_among_b(z, a_5, 6);
                if (!(among_var)) return 0;
                z->c = z->l - m_test3;
            }
            switch (among_var) {
                case 1:
                    {   int ret = slice_del(z);
                        if (ret < 0) return ret;
                    }
                    break;
                case 2:
                    {   int ret = slice_from_s(z, 2, s_6);
                        if (ret < 0) return ret;
                    }
                    break;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 4, s_7);
                if (ret < 0) return ret;
            }
            break;
        case 5:
            {   int ret = slice_from_s(z, 4, s_8);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_noun_double_declination(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_8, 6);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_from_s(z, 2, s_9);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 2, s_10);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int m_test1 = z->l - z->c;
                if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                z->c = z->l - m_test1;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test2 = z->l - z->c;
                if (!(find_among_b(z, a_7, 12))) return 0;
                z->c = z->l - m_test2;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_noun(struct SN_env * z) {
    int among_var;
    {   int m1 = z->l - z->c; (void)m1;
        {   int m2 = z->l - z->c; (void)m2;
            {   int ret = r_noun_impersonal_possessive(z);
                if (ret == 0) goto lab2;
                if (ret < 0) return ret;
            }
            goto lab1;
        lab2:
            z->c = z->l - m2;
            {   int ret = r_noun_possessive(z);
                if (ret == 0) goto lab0;
                if (ret < 0) return ret;
            }
        }
    lab1:
    lab0:
        z->c = z->l - m1;
    }
    z->ket = z->c;
    among_var = find_among_b(z, a_16, 35);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_from_s(z, 2, s_11);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 2, s_12);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int m_test3 = z->l - z->c;
                if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                z->c = z->l - m_test3;
            }
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test4 = z->l - z->c;
                if (!(find_among_b(z, a_9, 12))) return 0;
                z->c = z->l - m_test4;
            }
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int m_test5 = z->l - z->c;
                if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                z->c = z->l - m_test5;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test6 = z->l - z->c;
                if (!(find_among_b(z, a_11, 12))) return 0;
                z->c = z->l - m_test6;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 5:
            {   int m_test7 = z->l - z->c;
                {   int m8 = z->l - z->c; (void)m8;
                    if (z->c - 1 <= z->lb || z->p[z->c - 1] != 133) goto lab3;
                    if (!(find_among_b(z, a_13, 1))) goto lab3;
                    return 0;
                lab3:
                    z->c = z->l - m8;
                }
                z->c = z->l - m_test7;
            }
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 6:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 7:
            {   int m_test9 = z->l - z->c;
                {   int m10 = z->l - z->c; (void)m10;
                    if (z->c - 3 <= z->lb || (z->p[z->c - 1] != 131 && z->p[z->c - 1] != 175)) goto lab4;
                    if (!(find_among_b(z, a_14, 12))) goto lab4;
                    return 0;
                lab4:
                    z->c = z->l - m10;
                }
                z->c = z->l - m_test9;
            }
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 8:
            {   int m_test11 = z->l - z->c;
                {   int m12 = z->l - z->c; (void)m12;
                    if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                    z->c = z->l - m12;
                    {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                        if (ret < 0) return 0;
                        z->c = ret;
                    }
                }
                z->c = z->l - m_test11;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 9:
            {   int m_test13 = z->l - z->c;
                {   int m14 = z->l - z->c; (void)m14;
                    if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                    z->c = z->l - m14;
                    {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                        if (ret < 0) return 0;
                        z->c = ret;
                    }
                }
                z->c = z->l - m_test13;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test15 = z->l - z->c;
                if (!(find_among_b(z, a_15, 12))) return 0;
                z->c = z->l - m_test15;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_deverbative(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_18, 6);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test1 = z->l - z->c;
                if (z->c - 3 <= z->lb || z->p[z->c - 1] != 187) return 0;
                if (!(find_among_b(z, a_17, 1))) return 0;
                z->c = z->l - m_test1;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_verb_particles(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_22, 6);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test1 = z->l - z->c;
                if (!(find_among_b(z, a_19, 3))) return 0;
                z->c = z->l - m_test1;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test2 = z->l - z->c;
                if (!(find_among_b(z, a_21, 3))) return 0;
                z->c = z->l - m_test2;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_verb_number_person(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_24, 4);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 3);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            {   int m_test1 = z->l - z->c;
                if (z->c - 1 <= z->lb || (z->p[z->c - 1] != 131 && z->p[z->c - 1] != 175)) return 0;
                if (!(find_among_b(z, a_23, 2))) return 0;
                z->c = z->l - m_test1;
            }
            z->ket = z->c;
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 1);
                if (ret < 0) return 0;
                z->c = ret;
            }
            z->bra = z->c;
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_verb_tense_mood(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_26, 24);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int m_test1 = z->l - z->c;
                {   int m2 = z->l - z->c; (void)m2;
                    if (z->c - 1 <= z->lb || z->p[z->c - 1] != 133) goto lab0;
                    if (!(find_among_b(z, a_25, 1))) goto lab0;
                    return 0;
                lab0:
                    z->c = z->l - m2;
                }
                z->c = z->l - m_test1;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_verb_stem(struct SN_env * z) {
    int among_var;
    {   int m1 = z->l - z->c; (void)m1;
        {   int ret = r_verb_particles(z);
            if (ret == 0) { z->c = z->l - m1; goto lab0; }
            if (ret < 0) return ret;
        }
    lab0:
        ;
    }
    {   int m2 = z->l - z->c; (void)m2;
        {   int ret = r_verb_number_person(z);
            if (ret == 0) { z->c = z->l - m2; goto lab1; }
            if (ret < 0) return ret;
        }
    lab1:
        ;
    }
    {   int m3 = z->l - z->c; (void)m3;
        {   int ret = r_verb_tense_mood(z);
            if (ret == 0) { z->c = z->l - m3; goto lab2; }
            if (ret < 0) return ret;
        }
    lab2:
        ;
    }
    z->ket = z->c;
    among_var = find_among_b(z, a_27, 15);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int ret = skip_b_utf8(z->p, z->c, z->lb, 2);
                if (ret < 0) return 0;
                z->c = ret;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_from_s(z, 2, s_13);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int ret = slice_from_s(z, 2, s_14);
                if (ret < 0) return ret;
            }
            break;
        case 4:
            {   int ret = slice_from_s(z, 2, s_15);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

static int r_gerund(struct SN_env * z) {
    int among_var;
    z->ket = z->c;
    among_var = find_among_b(z, a_28, 20);
    if (!(among_var)) return 0;
    z->bra = z->c;
    switch (among_var) {
        case 1:
            {   int m_test1 = z->l - z->c;
                if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) return 0;
                z->c = z->l - m_test1;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 2:
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
        case 3:
            {   int m_test2 = z->l - z->c;
                {   int m3 = z->l - z->c; (void)m3;
                    if (in_grouping_b_U(z, g_vowel, 1072, 1257, 0)) goto lab0;
                    return 0;
                lab0:
                    z->c = z->l - m3;
                }
                z->c = z->l - m_test2;
            }
            {   int ret = slice_del(z);
                if (ret < 0) return ret;
            }
            break;
    }
    return 1;
}

extern int kalmyk_UTF_8_stem(struct SN_env * z) {
    z->lb = z->c; z->c = z->l;

    {   int m1 = z->l - z->c; (void)m1;
        {   int m2 = z->l - z->c; (void)m2;
            {   int ret = r_gerund(z);
                if (ret == 0) { z->c = z->l - m2; goto lab2; }
                if (ret < 0) return ret;
            }
        lab2:
            ;
        }
        {   int ret = r_verb_stem(z);
            if (ret == 0) goto lab1;
            if (ret < 0) return ret;
        }
        goto lab0;
    lab1:
        z->c = z->l - m1;
        {   int m3 = z->l - z->c; (void)m3;
            {   int ret = r_noun(z);
                if (ret < 0) return ret;
            }
            z->c = z->l - m3;
        }
        {   int m4 = z->l - z->c; (void)m4;
            {   int ret = r_noun_double_declination(z);
                if (ret < 0) return ret;
            }
            z->c = z->l - m4;
        }
        {   int m5 = z->l - z->c; (void)m5;
            {   int ret = r_noun_plural(z);
                if (ret < 0) return ret;
            }
            z->c = z->l - m5;
        }
        {   int m6 = z->l - z->c; (void)m6;
            {   int ret = r_deverbative(z);
                if (ret < 0) return ret;
            }
            z->c = z->l - m6;
        }
    }
lab0:
    z->c = z->lb;
    return 1;
}

extern struct SN_env * kalmyk_UTF_8_create_env(void) { return SN_create_env(0, 0); }

extern void kalmyk_UTF_8_close_env(struct SN_env * z) { SN_close_env(z, 0); }

